// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/NFortun/Astrobot-Sdk/models"
)

// GetImageOfTheDayReader is a Reader for the GetImageOfTheDay structure.
type GetImageOfTheDayReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetImageOfTheDayReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetImageOfTheDayOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetImageOfTheDayDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetImageOfTheDayOK creates a GetImageOfTheDayOK with default headers values
func NewGetImageOfTheDayOK() *GetImageOfTheDayOK {
	return &GetImageOfTheDayOK{}
}

/*
GetImageOfTheDayOK describes a response with status code 200, with default header values.

Success
*/
type GetImageOfTheDayOK struct {
	Payload *models.ImageResponse
}

// IsSuccess returns true when this get image of the day o k response has a 2xx status code
func (o *GetImageOfTheDayOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get image of the day o k response has a 3xx status code
func (o *GetImageOfTheDayOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get image of the day o k response has a 4xx status code
func (o *GetImageOfTheDayOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get image of the day o k response has a 5xx status code
func (o *GetImageOfTheDayOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get image of the day o k response a status code equal to that given
func (o *GetImageOfTheDayOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetImageOfTheDayOK) Error() string {
	return fmt.Sprintf("[GET /imageoftheday][%d] getImageOfTheDayOK  %+v", 200, o.Payload)
}

func (o *GetImageOfTheDayOK) String() string {
	return fmt.Sprintf("[GET /imageoftheday][%d] getImageOfTheDayOK  %+v", 200, o.Payload)
}

func (o *GetImageOfTheDayOK) GetPayload() *models.ImageResponse {
	return o.Payload
}

func (o *GetImageOfTheDayOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ImageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetImageOfTheDayDefault creates a GetImageOfTheDayDefault with default headers values
func NewGetImageOfTheDayDefault(code int) *GetImageOfTheDayDefault {
	return &GetImageOfTheDayDefault{
		_statusCode: code,
	}
}

/*
GetImageOfTheDayDefault describes a response with status code -1, with default header values.

default error message
*/
type GetImageOfTheDayDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get image of the day default response
func (o *GetImageOfTheDayDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get image of the day default response has a 2xx status code
func (o *GetImageOfTheDayDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get image of the day default response has a 3xx status code
func (o *GetImageOfTheDayDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get image of the day default response has a 4xx status code
func (o *GetImageOfTheDayDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get image of the day default response has a 5xx status code
func (o *GetImageOfTheDayDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get image of the day default response a status code equal to that given
func (o *GetImageOfTheDayDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetImageOfTheDayDefault) Error() string {
	return fmt.Sprintf("[GET /imageoftheday][%d] GetImageOfTheDay default  %+v", o._statusCode, o.Payload)
}

func (o *GetImageOfTheDayDefault) String() string {
	return fmt.Sprintf("[GET /imageoftheday][%d] GetImageOfTheDay default  %+v", o._statusCode, o.Payload)
}

func (o *GetImageOfTheDayDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetImageOfTheDayDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
